services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: my_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "events.taxonomy:3:1, bets.state:3:1"
    restart: on-failure
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 35
      start_period: 10s

  dbui:
    image: dpage/pgadmin4:6
    ports: [ "8080:8080" ]
    environment:
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DEFAULT_EMAIL: estupian@email.com
      PGADMIN_DEFAULT_PASSWORD: something_harder

  db:
    image: postgres:14
    ports: ["5432:5432"]
    hostname: db
    environment:
      POSTGRES_USER: estupian
      POSTGRES_DB: database
      POSTGRES_PASSWORD: something_harder

  cruds:
    build: ./CRUDs/
    depends_on:
        - db
    ports:
      ["3000:3000"]

  events:
    build: ./CRUDs_events/
    depends_on:
      - db
      - event_writer
    ports:
      ["8000:8000"]

  event_writer:
    build: ./EventWriter/
    depends_on:
      - kafka

  bet_scorer:
    build: ./BetScorer/
    depends_on:
      - kafka

  bet_writer:
    build: ./BetWriter/
    depends_on:
      - kafka